# Generated by Django 4.1.7 on 2023-03-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0004_city_alter_specialist_activity_and_more")]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Короткое описание"
            ),
        ),
    ]
