# Generated by Django 4.1.7 on 2023-03-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0005_alter_service_name_alter_service_short_description")]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("sale", models.CharField(max_length=100, verbose_name="Скидка")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("photo", models.ImageField(upload_to="", verbose_name="Фото")),
                ("date_start", models.DateField(verbose_name="Начало акции")),
                ("date_end", models.DateField(verbose_name="Конец акции")),
                ("on_main", models.BooleanField(verbose_name="Выводить на главной")),
            ],
            options={"verbose_name": "Акция", "verbose_name_plural": "Акции"},
        ),
        migrations.AlterField(
            model_name="updater",
            name="start_update",
            field=models.DateTimeField(verbose_name="Время начала"),
        ),
    ]
