# Generated by Django 4.1.7 on 2023-03-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0007_rating")]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="reviews_count",
            field=models.FileField(blank=True, upload_to="", verbose_name="Количество отзывов"),
        )
    ]
