# Generated by Django 4.1.7 on 2023-03-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0008_alter_rating_reviews_count")]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="photo",
            field=models.FileField(upload_to="", verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="rating",
            name="reviews_count",
            field=models.TextField(blank=True, verbose_name="Количество отзывов"),
        ),
    ]
