# Generated by Django 4.1.7 on 2023-03-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0010_rating_link")]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
                ("document", models.FileField(upload_to="", verbose_name="Документ")),
                ("link", models.URLField(blank=True, max_length=255, verbose_name="Ссылка")),
            ],
            options={"verbose_name": "Лицензия", "verbose_name_plural": "Лицензии"},
        )
    ]
