# Generated by Django 4.1.7 on 2023-03-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0011_license")]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
                ("file", models.FileField(upload_to="", verbose_name="Документ")),
                ("link", models.URLField(blank=True, max_length=255, verbose_name="Ссылка")),
            ],
            options={"verbose_name": "Документ", "verbose_name_plural": "Документы"},
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
            ],
            options={"verbose_name": "Документ", "verbose_name_plural": "Документы"},
        ),
        migrations.DeleteModel(name="License"),
        migrations.AddField(
            model_name="document",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="app.documentcategory",
                verbose_name="Категория",
            ),
        ),
    ]
