# Generated by Django 4.1.7 on 2023-03-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0012_document_documentcategory_delete_license_and_more")]

    operations = [
        migrations.AlterModelOptions(
            name="documentcategory",
            options={
                "verbose_name": "Категория документа",
                "verbose_name_plural": "Категории документов",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="preparation",
            field=models.TextField(blank=True, verbose_name="Подготовка"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, default=1, verbose_name="Короткое описание"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="short_description",
            field=models.CharField(
                blank=True, default=1, max_length=255, verbose_name="Короткое описание"
            ),
            preserve_default=False,
        ),
    ]
