# Generated by Django 4.1.7 on 2023-03-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0013_alter_documentcategory_options_service_preparation_and_more")]

    operations = [
        migrations.CreateModel(
            name="ServiceCatalog",
            fields=[
                (
                    "guid",
                    models.CharField(
                        max_length=36, primary_key=True, serialize=False, verbose_name="GUID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={"verbose_name": "Каталог услуг", "verbose_name_plural": "Каталоги услуг"},
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
    ]
