# Generated by Django 4.1.7 on 2023-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0014_servicecatalog_alter_service_description")]

    operations = [
        migrations.RemoveField(model_name="service", name="level"),
        migrations.RemoveField(model_name="service", name="lft"),
        migrations.RemoveField(model_name="service", name="parent"),
        migrations.RemoveField(model_name="service", name="rght"),
        migrations.RemoveField(model_name="service", name="tree_id"),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "guid",
                    models.CharField(
                        max_length=36, primary_key=True, serialize=False, verbose_name="GUID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "catalogs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="categories",
                        to="app.servicecatalog",
                        verbose_name="Каталоги",
                    ),
                ),
            ],
            options={"verbose_name": "Категория услуг", "verbose_name_plural": "Категории услуг"},
        ),
        migrations.AddField(
            model_name="service",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="services",
                to="app.servicecategory",
                verbose_name="Категории",
            ),
        ),
    ]
