# Generated by Django 4.1.7 on 2023-03-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0016_servicecategory_level_servicecategory_lft_and_more")]

    operations = [
        migrations.RemoveField(model_name="service", name="is_group"),
        migrations.RemoveField(model_name="service", name="on_main"),
        migrations.AddField(
            model_name="servicecategory",
            name="is_active",
            field=models.BooleanField(default=1, verbose_name="Активно"),
            preserve_default=False,
        ),
    ]
