# Generated by Django 4.1.7 on 2023-03-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0017_remove_service_is_group_remove_service_on_main_and_more")]

    operations = [
        migrations.RemoveField(model_name="servicecategory", name="catalogs"),
        migrations.AddField(
            model_name="servicecategory",
            name="catalog",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="app.servicecatalog",
                verbose_name="Каталог",
            ),
            preserve_default=False,
        ),
    ]
