# Generated by Django 4.1.7 on 2023-03-12 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("app", "0018_remove_servicecategory_catalogs_and_more")]

    operations = [migrations.RemoveField(model_name="servicecategory", name="is_active")]
