# Generated by Django 4.1.7 on 2023-03-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("app", "0021_license")]

    operations = [
        migrations.AddField(
            model_name="license",
            name="number",
            field=models.CharField(default=1, max_length=50, verbose_name="Номер"),
            preserve_default=False,
        )
    ]
