# Generated by Django 4.1.7 on 2023-03-07 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "guid",
                    models.CharField(
                        max_length=36, primary_key=True, serialize=False, verbose_name="GUID 1C"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("surname", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Отчество"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Фотография"
                    ),
                ),
                ("start_work_date", models.DateField(verbose_name="Начало работы")),
                ("education", models.TextField(blank=True, null=True, verbose_name="Образование")),
                ("activity", models.TextField(blank=True, null=True, verbose_name="Образование")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Образование"),
                ),
                ("titles", models.TextField(blank=True, null=True, verbose_name="Образование")),
                ("can_adult", models.BooleanField(verbose_name="Принимает взрослых")),
                ("can_child", models.BooleanField(verbose_name="Принимает детей")),
                ("can_online", models.BooleanField(verbose_name="Проводит онлайн консультацию")),
                ("on_main", models.BooleanField(verbose_name="Выводить на главной")),
                ("is_active", models.BooleanField(verbose_name="Активно")),
            ],
            options={"verbose_name": "Специализация", "verbose_name_plural": "Специализации"},
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "guid",
                    models.CharField(
                        max_length=36, primary_key=True, serialize=False, verbose_name="GUID 1C"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
            ],
            options={"verbose_name": "Специальность", "verbose_name_plural": "Специальности"},
        ),
        migrations.CreateModel(
            name="SpecialistCertificate",
            fields=[
                (
                    "guid",
                    models.CharField(
                        max_length=36, primary_key=True, serialize=False, verbose_name="GUID 1C"
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Имя")),
                ("file", models.FileField(upload_to="", verbose_name="Документ")),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="specialists.specialist",
                        verbose_name="Специалист",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="specialist",
            name="specializations",
            field=models.ManyToManyField(
                related_name="specialists",
                to="specialists.specialization",
                verbose_name="Специализации",
            ),
        ),
    ]
