# Generated by Django 4.1.7 on 2023-03-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("specialists", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="specialist",
            options={"verbose_name": "Специалист", "verbose_name_plural": "Специалисты"},
        ),
        migrations.AlterField(
            model_name="specialist",
            name="activity",
            field=models.TextField(blank=True, null=True, verbose_name="Деятельность"),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="specialist",
            name="titles",
            field=models.TextField(blank=True, null=True, verbose_name="Титулы"),
        ),
    ]
