# Generated by Django 4.1.7 on 2023-03-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Updater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_update", models.DateTimeField(verbose_name="Время налача")),
                (
                    "end_update",
                    models.DateTimeField(blank=True, null=True, verbose_name="Время окончания"),
                ),
                ("status", models.CharField(max_length=20, verbose_name="Статус")),
                ("error_log", models.TextField(verbose_name="Текст ошибки")),
            ],
        )
    ]
