# Generated by Django 4.1.7 on 2023-03-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("updater", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="updater",
            options={"verbose_name": "Обновление", "verbose_name_plural": "Обновления"},
        ),
        migrations.AlterField(
            model_name="updater",
            name="error_log",
            field=models.TextField(blank=True, null=True, verbose_name="Текст ошибки"),
        ),
    ]
